apiVersion: v1
kind: ServiceAccount
metadata:
  name: scanipy-worker
  namespace: scanipy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scanipy-api
  namespace: scanipy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scanipy-api-role
  namespace: scanipy
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scanipy-api-binding
  namespace: scanipy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scanipy-api-role
subjects:
- kind: ServiceAccount
  name: scanipy-api
  namespace: scanipy
